### ISSUE TITLE
Issue related to base branch artifact

### ISSUE THREAD

**Issue by aashish-fiftyfive** [clearlyip/code-coverage-report-action#11]
I am unable to debug that where does the action finds for the base ref artifacts, if it looks for the previous successful workflow run then I have that artifacts in previous one, I am sharing the logs here and screenshot also - 

Looking for artifact "coverage-release-v1.74.0-CLOUDTEAM-11889" in the following workflows: jpi-cloud-usermanagement
Warning: No artifacts found for the following workspaces: jpi-cloud-usermanagement

![image](https://github.com/clearlyip/code-coverage-report-action/assets/119846734/6ffe3456-d77c-42f4-8f91-0f36fc0b5d68)

**Comment by aashish-fiftyfive** [comment]
Does your application requires any specific permission on workflows to fetch the artifact?

**Comment by aashish-fiftyfive** [comment]
My repository is internal not private, does this action only works for private repositories?

**Comment by tm1000** [comment]
Hi

I'll need more information here (logs) or better yet a test repo to see where you've gone wrong.

> Does your application requires any specific permission on workflows to fetch the artifact?

No

> My repository is internal not private, does this action only works for private repositories?

There are only two types of github repositories. Public and private.

**Comment by craigbroadman** [comment]
I have it working on an internal repository.

One thing to check is do you name your jobs (like below):

```
jobs:
  build:
    name: CI - Build and Test
```

If so, try specifting the artifact_download_workflow_names as below:

```
- name: Generate Coverage Report
      uses: clearlyip/code-coverage-report-action@v3
      if: steps.findUnitTestsDll.outputs.hasFoundTestDll == 'true'
      id: code_coverage_report_action
      with:
        badge: true
        markdown_filename: code-coverage-results
        filename: 'test-results/cobertura.xml'
        fail_on_negative_difference: true
        negative_difference_threshold: 0.005 #0.5%
        artifact_download_workflow_names: 'CI - Build and Test'
```

**Comment by ryan-corn-aeroflow** [comment]
I am having this same issue:
`No artifacts found for the following workspaces: Code-Coverage-Cron`

I have 
```      
- uses: clearlyip/code-coverage-report-action@v4
        with:
          filename: 'coverage/clover.xml'
          artifact_download_workflow_names: 'Code-Coverage-Cron'
```

The name of the job is 
```
name: 'Code-Coverage-Cron'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 
      - name: Run phpunit coverage
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit -c dev/tests/unit/phpunit.azure.xml --testsuite App_Code_Unit_Tests --coverage-clover 'coverage/clover.xml'

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-develop
          path: coverage/clover.xml

      - uses: clearlyip/code-coverage-report-action@v4
        with:
          filename: 'coverage/clover.xml'
          artifact_download_workflow_names: 'Code-Coverage-Cron'
```
This is with a  private repo.
