### ISSUE TITLE
Baseline coverage not created

### ISSUE THREAD

**Issue by npham-ipipeline** [clearlyip/code-coverage-report-action#112]
Hi,

I have an action that generate a baseline for a branch upon branch creation i.e. triggered using `create` trigger event. Step is as below.

```
    - name: Generate Coverage Report Branch Creation
      if: ${{ github.actor != 'dependabot[bot]' && github.event_name == 'create' && steps.runUnitTests.outputs.unitTestProjectsFound == 'true'}}
      uses: clearlyip/code-coverage-report-action@v4.1.1
      with:
        filename: './UnitTestResults/Combined-Cobertura/Cobertura.xml'
        retention_days: 14
        badge: true
```
I then get
```
Run clearlyip/code-coverage-report-action@v4.1.1
  with:
    filename: ./UnitTestResults/Combined-Cobertura/Cobertura.xml
    retention_days: 14
    badge: true
    github_token: ***
    markdown_filename: code-coverage-results
    overall_coverage_fail_threshold: 0
    file_coverage_error_min: 50
    file_coverage_warning_max: 75
    fail_on_negative_difference: false
    artifact_name: coverage-%name%
    negative_difference_by: package
    negative_difference_threshold: 0
```

The branch name is sprint/NTT-7, so I expect a "coverage-sprint-NTT-7" artifact to be created but it wasn't. Similar step successfully create an artifact if triggered by either `workflow_dispatch` or `schedule`.
