### ISSUE TITLE
negative_difference_threshold is not working.

### ISSUE THREAD

**Issue by craigbroadman** [clearlyip/code-coverage-report-action#39]
Has this ever been implemented? 

Reference: https://github.com/clearlyip/code-coverage-report-action/blob/4b94fffa3514ccd62b8023f6c6dc21257ca29de6/action.yml#L50

```yml
negative_difference_threshold:
    description: 'The percentage drop in coverage that should be allowed, in decimal form (0.05 == 5%). The default value is 0.'
    required: false
    default: '0'
```

If not, I'm happy to collaborate on the implementation 👍🏼
