### ISSUE TITLE
Wrong artiface name when generating baseline coverage 

### ISSUE THREAD

**Issue by npham-ipipeline** [clearlyip/code-coverage-report-action#51]
Hi,

I’m using the below step to generate baseline test coverage in dev branch. Instead of the default artifact name “coverage-dev”, the artifact name uploaded is “aaaaacoverage-dev” instead. Is there a way to fix this issue?

```

jobs:
  baseline:
    name: baseline
    runs-on: windows-latest

    steps:
    - name: Generate Coverage Report
      uses: clearlyip/code-coverage-report-action@v4
      with:
        filename: './UnitTestResults/Combined-Cobertura/Cobertura.xml'
        retention_days: 1
```

Here are the logs

```
Run clearlyip/code-coverage-report-action@v4
  with:
    filename: ./UnitTestResults/Combined-Cobertura/Cobertura.xml
    retention_days: 1
    github_token: ***
    markdown_filename: code-coverage-results
    badge: false
    overall_coverage_fail_threshold: 0
    file_coverage_error_min: 50
    file_coverage_warning_max: 75
    fail_on_negative_difference: false
    artifact_name: coverage-%name%
    negative_difference_by: package
    negative_difference_threshold: 0
  env:
    NUGET: C:\hostedtoolcache\windows\nuget.exe\6.9.1\x64/nuget.exe
Uploading ./UnitTestResults/Combined-Cobertura/Cobertura.xml...
Artifact name is valid!
Root directory input is valid!
Beginning upload of artifact content to blob storage
Uploaded bytes 8388608
Uploaded bytes 10449320
Finished uploading artifact content to blob storage!
SHA256 hash of uploaded artifact zip is bb2cd4a32a142328fee49a603f336087b23383f10551436c2a56715be353cca9
Finalizing artifact upload
Artifact aaaaacoverage-dev.zip successfully finalized. Artifact ID 1347420972
Artifact Metadata:
{
    "size": 10449320,
    "id": [1347420972](tel:1347420972)
}
Complete
Parsing coverage file: ./UnitTestResults/Combined-Cobertura/Cobertura.xml...
Detected a Cobertura File at ./UnitTestResults/Combined-Cobertura/Cobertura.xml
Complete
Generating markdown from ...
Writing results to code-coverage-results.md
Writing job summary
Complete
```

Thanks,
Nhat
