### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by prem-prakash** [clearlyip/code-coverage-report-action#64]
```yml
      - name: Generate Coverage Report
        uses: clearlyip/code-coverage-report-action@v5
        with:
          filename: 'coverage/coverage.xml'
          fail_on_negative_difference: true
          artifact_download_workflow_names: 'Lint and Test'
          only_list_changed_files: true
```

I get

```sh
Run clearlyip/code-coverage-report-action@v5
  with:
    filename: coverage/coverage.xml
    fail_on_negative_difference: true
    artifact_download_workflow_names: Lint and Test
    only_list_changed_files: true
    github_token: ***
    markdown_filename: code-coverage-results
    badge: false
    overall_coverage_fail_threshold: 0
    file_coverage_error_min: 50
    file_coverage_warning_max: 75
    artifact_name: coverage-%name%
    negative_difference_by: package
    negative_difference_threshold: 0
(https://github.com/***/***/actions/runs/****/job/*****#step:7:3)40558746-1
Looking for artifact "coverage-main" in the following workflows: Lint and Test
Error: Resource not accessible by integration - https://docs.github.com/rest/actions/workflow-runs#list-workflow-runs-for-a-repository
```

Is there any special permission for this?

I am pretty sure there is the artifact "coverage-main" in the workflow "Lint and Test".

I tried:

```yml
permissions: read-all
```

and

```yml
permissions:
  pull-requests: write
  actions: read
  contents: read
```
